<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="P_CraneSim" Id="{abd16a88-c182-46f2-9f6f-a5822b2fe25a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_CraneSim
VAR
	fbCraneSim		: FB_CraneSimulator;
	bSimulatorOn			: BOOL;
	fValeInput				: LREAL;
	fCylinderPosition		: LREAL;
	fPistonSidePressure			: LREAL;
	fRodSidePressure		: LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbCraneSim(
	ssMethodType := BOOL_TO_SINT(bSimulatorOn),
	uDCV := fValeInput,
	xm => fCylinderPosition,
	ppbar => fPistonSidePressure,
	prbar => fRodSidePressure
);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>